run:

    - shallow-classifier_after-aspp_false-os_4-ss_2:
        nb_epochs: 100
        mask_value: null
        weights: null 
        weights_dir: /home/ericp/tree_canopy_fcn/repo/cli/weights
        lrs:
            - 0.001
            # - 0.0001
        patience: 6
        criterion:
            accuracy_activation: softmax
            ignore_index: null
            weights:
              - 1.0
              - 1.1
              - 1.1
              - 1.1
              - 0.95
              # - 1.0
              # - 1.0
              # - 1.0
              # - 1.0
              # - 1.0
        optimizer:
            name: radam
        loaders:         
            batch_size: 6
            no_data_value: 4
            float_cropping: 64

models:
    shallow-classifier_after-aspp_false-os_4-ss_2:    
        in_ch: 5
        out_ch: 5
        aspp: False
        backbone: xception
        classifier_position: after
        backbone_config:
                bottleneck_depth: 2
                output_stride: 4
                stride_states: [2]
                xblock_chs: [128]
                exit_xblock_ch: 256
                exit_stack_chs: [512]


run_notes:

    - shallow-classifier_after-aspp_false-os_4-ss_2:
      - pass

