run:

    - green_bu_plieades-shallow:
        nb_epochs: 50
        mask_value: 9
        weights: null 
        weights_dir: /home/ericp/tree_canopy_fcn/repo/cli/weights
        lrs:
            - 0.001
        patience: 4
        criterion:
            accuracy_activation: softmax
            ignore_index: 9
            weights:
              - 1.0
              - 1.0
              - 1.0
              - 1.0
              - 1.0
              - 1.0
              - 1.0
              - 1.0
              - 1.0   
              - 0.95
        optimizer:
            name: radam
        loaders:         
            batch_size: 6
            no_data_value: 9
            float_cropping: 64

models:
    green_bu_plieades-shallow:    
        in_ch: 6
        out_ch: 10
        aspp: False
        backbone: xception
        classifier_position: after
        backbone_config:
                bottleneck_depth: 2
                output_stride: 4
                stride_states: [2]
                xblock_chs: [128]
                exit_xblock_ch: 256
                exit_stack_chs: [512]


run_notes:

    - green_bu_plieades-shallow:
      - pass

