run:

    - greenspace-naip-shallow:
        nb_epochs: 50
        mask_value: null
        weights: null 
        weights_dir: /home/ericp/tree_canopy_fcn/repo/cli/weights
        lrs:
            - 0.001
        patience: 4
        criterion:
            accuracy_activation: softmax
            ignore_index: null
            weights:
              - 1.0
              - 1.1
              - 1.1
              - 1.1
              - 0.95
        optimizer:
            name: radam
        loaders:         
            batch_size: 6
            no_data_value: no_data_last
            float_cropping: 64

models:
    greenspace-naip-shallow:    
        in_ch: 5
        out_ch: 5
        aspp: False
        backbone: xception
        classifier_position: after
        backbone_config:
                bottleneck_depth: 2
                output_stride: 4
                stride_states: [2]
                xblock_chs: [128]
                exit_xblock_ch: 256
                exit_stack_chs: [512]


run_notes:

    - greenspace-naip-shallow:
        greenspace_naip.greenspace-naip-shallow.2020-05-13T05:42:54:
            best_epoch: 52
            best_loss: 0.5095073076394888
            best_acc: 0.79332208327758
            weights: greenspace_naip.greenspace-naip-shallow.best.2020-05-13T05:42:54.p

