run:

    - green_bu-shallow:
        nb_epochs: 100
        mask_value: 9
        weights: green_bu_naip.green_bu-shallow.best.2020-05-13T11:02:30.p 
        weights_dir: /home/ericp/tree_canopy_fcn/repo/cli/weights
        lrs:
            - 0.001
        patience: 6
        criterion:
            accuracy_activation: softmax
            ignore_index: 9
            weights:
              - 1.0
              - 1.0
              - 1.0
              - 1.0
              - 1.0
              - 1.0
              - 1.0
              - 1.0
              - 1.0   
              - 0.95
        optimizer:
            name: radam
        loaders:         
            batch_size: 6
            no_data_value: 9
            float_cropping: 64

models:
    green_bu-shallow:    
        in_ch: 6
        out_ch: 10
        aspp: False
        backbone: xception
        classifier_position: after
        backbone_config:
                bottleneck_depth: 2
                output_stride: 4
                stride_states: [2]
                xblock_chs: [128]
                exit_xblock_ch: 256
                exit_stack_chs: [512]


run_notes:

    - green_bu_naip-shallow:
        green_bu_naip.green_bu-shallow.2020-05-13T11:02:30.p:
            note: >-
              accidently ran with all data instead of 2015/2016. 
              nb_bathes=(349,99).
              stopped after 7 epochs
            best_epoch: 52
            best_loss: 0.826
            best_acc: 0.703
            weights: green_bu_naip.green_bu-shallow.best.2020-05-13T11:02:30.p
