run:

    # - shallow-classifier_after-aspp_false-os_4-ss_2:
    #     weights: false
    #     weights_dir: /home/ericp/tree_canopy_fcn/repo/cli/weights
    #     lrs:
    #         - 0.001
    #         - 0.0001
    #     criterion:
    #         accuracy_activation: sigmoid
    #         pos_weight: 
    #             - 2
    #     optimizer:
    #         name: radam
    #     loaders:         
    #         batch_size: 12

    - shallow-classifier_after-aspp_false-os_4-ss_2:
        weights: false
        weights_dir: /home/ericp/tree_canopy_fcn/repo/cli/weights
        lrs:
            - 0.001
        criterion:
            accuracy_activation: sigmoid
            pos_weight: 
                - 3.5
        optimizer:
            name: radam
        loaders:         
            batch_size: 12


models:
    shallow-classifier_after-aspp_false-os_4-ss_2:    
        in_ch: 5
        out_ch: 1
        aspp: False
        backbone: xception
        classifier_position: after
        backbone_config:
                bottleneck_depth: 2
                output_stride: 4
                stride_states: [2]
                xblock_chs: [128]
                exit_xblock_ch: 256
                exit_stack_chs: [512]


run_notes:

    - shallow-classifier_after-aspp_false-os_4-ss_2:

        runs:
            - weights: false
              pos_weight: 2

              lrs:
                - lr: 0.001
                  best_epoch: 44
                  best_loss: 0.24332001843513587
                  best_acc: 0.9300750830234625
                  output_weights: treecover.shallow-classifier_after-aspp_false-os_4-ss_2.best.2020-01-30T17:32:44.p
                
                - lr: 0.0001
                  best_epoch: 4
                  best_loss: 0.23940131794183683
                  best_acc: 0.930449475080539
                  output_weights: treecover.shallow-classifier_after-aspp_false-os_4-ss_2.best.2020-01-30T19:23:06.p

            - weights: false
              pos_weight: 3.5
              lrs:
                - lr: 0.001
                  best_epoch: 49
                  best_loss: 0.3090818940829008
                  best_acc: 0.9166554762766912
                  output_weights: treecover.shallow-classifier_after-aspp_false-os_4-ss_2.best.2020-01-30T20:36:34.p



