run:
    - shallow-classifier_after-aspp_false-os_4-ss_2:
        weights: false
        weights_dir: /home/ericp/tree_canopy_fcn/repo/cli/weights
        lrs:
            - 0.001
            - 0.0001
        criterion:
            accuracy_activation: sigmoid
            pos_weight: 
                - 2
        optimizer:
            name: radam
        loaders:         
            batch_size: 12

    - shallow-classifier_after-aspp_false-os_4-ss_2:
        weights: false
        weights_dir: /home/ericp/tree_canopy_fcn/repo/cli/weights
        lrs:
            - 0.001
            - 0.0001
        criterion:
            accuracy_activation: sigmoid
            pos_weight: 
                - 3.5
        optimizer:
            name: radam
        loaders:         
            batch_size: 12


models:
    shallow-classifier_after-aspp_false-os_4-ss_2:    
        in_ch: 5
        out_ch: 1
        aspp: False
        backbone: xception
        classifier_position: after
        backbone_config:
                bottleneck_depth: 2
                output_stride: 4
                stride_states: [2]
                xblock_chs: [128]
                exit_xblock_ch: 256
                exit_stack_chs: [512]



run_notes:
    - shallow-classifier_after-aspp_false-os_4-ss_2:
        -runs:
            - lrs: [0.001,0.0001]
              weights: false
              pos_weight: 2
              best_acc: --
              best_loss: --
              best_epoch: --
              output_weights: --

            - lrs: [0.001,0.0001]
              weights: false
              pos_weight: 3.5
              best_acc: --
              best_loss: --
              best_epoch: --
              output_weights: --