product:
    id: dev1
    resolution: 1m
    readers: 
      - 'org:wri'
    notes: >-
      tree canopy predictions for LA
    
bands:
    - name: tree
      description: no-tree, tree, mask
      data_range: [0,255]
      display_range: [0,255]
      nodata: 2
      class_labels:
        - Not-Tree
        - Tree
        - No Data
      colormap:
        - [106, 222, 172, 255]
        - [255, 94, 97, 255]
        - [119, 119, 119, 255]
      color: Palette
      type: class
      data_type: Byte
      resolution: 
        value: 1
        unit: meters
    - name: scores
      description: output probablity from model
      data_range: [0.0,1.0]
      display_range: [0,1.0]
      color: Undefined
      data_type: Float32
      resolution: 
        value: 1
        unit: meters
